### PR TITLE
Feat/6 upload presaved

### PR DESCRIPTION
**Pull request by arunge**
#6

- shifted the down/upload of models to a new sidepanel on the right side (1)
- extracted a module to down and upload models
- the content of the help is now saved into a help.html file when downloading a model object
- new directory for presaved models
- option to load presaved models (1)
  - replace `load`of RData file into global environment with `readRDS` as local object
  - use a path variable
- select input instead of buttons for tables (2)
- add the model output itself to the downloadable model object

image

### CODE REVIEW

**Comment by arunge** [comment]
@jroachell15 Could you test the new features (1,2) described here https://github.com/Pandora-IsoMemo/resources/pull/11#issue-1165181623 ?

**Review by jroachell15 — APPROVED** [review]
looks good! I have tested the app as well!

**Comment by jroachell15** [comment]
@arunge I just noticed that when i hit the button `load remote model` I see _test model with oxcal_ under the `notes` section. Is that part of the implementation?

image

**Comment by arunge** [comment]
@jroachell15 yes, exactly, these are the notes that were stored when I downloaded the model object that I am using for testing. The note reminds me that I checked the box for "oxcal export" before running the model, so one can use this test object to test also the oxcal output without recalculating a model.

**Pull request merged**
