### PR TITLE
Version 23.02.4: switch to kaleido

### PR DESCRIPTION
**Pull request by arunge**
### Bug fixes
- switch to kaleido package instead of orca for plotly export (#76)

### CODE REVIEW

**Comment by arunge** [comment]
@jan-abel-inwt As you suggested, I switched to kaleido. Now it works at least locally, but i had to install new packages as described in the documentation of the `save_image` function (1). 

- [ ] Can you install the required packages for online?
- [ ]  And review the changes of this PR?

image

Locally, after adding the package `reticulate` and starting the app, an automatic request to install other missing packages was printed into the console. After confirming to the missing installations and restarting the app, I could export plots. One can test this after loading some example data (1), going to "Model characteristics" and exporting the plot (2) and (3).

image

**Review by jan-abel-inwt — COMMENTED** [review]
looks good! And now we don't need the orca dependency any more. i will remove it in the base-image repo

**Comment by jan-abel-inwt** [comment]
There is still an error on jenkins with the arguments of the function below.

```
Note: possible error in 'tryCatchWithWarningsAndErrors(errorTitle = "Export failed", ': unused arguments (errorTitle = "Export failed", alertStyle = "shinyalert") 
See ‘/tmp/RtmpoCvYvf/ReSources.Rcheck/00install.out’ for details.
```

**Comment by arunge** [comment]
@jan-abel-inwt in order to make the checks run again, I need the most recent version of dataTools here. For this we require the package rgpt3 here, also. After you added it here, the checks should be fine and you can continue with https://github.com/Pandora-IsoMemo/resources/pull/79#issuecomment-1437980101
Thanks! :slightly_smiling_face:

**Comment by jan-abel-inwt** [comment]
* I added the remote repo of the rgpt pkg
* I added the install instruction of miniconda, reticulate, kaleido & plotly in the local Dockerfile
   *  if the feature is working, we have to move these instruction to the base-image dockerfile later.

**Comment by jan-abel-inwt** [comment]
This is still not working! I'll look into it tomorrow morning.

image

**Pull request merged**
